title: Plant Translocation Network
description: An international network of researchers, practitioners and policymakers using plant translocations to address biodiversity loss
twitter_username: SarahEDalrymple
author: Sarah E. Dalrymple
year: 2021
search: true
